AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE,HEAD'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: python3.12

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Environment:
        Variables:
          SPOONACULAR_API_KEY: 9e2fbc476a004871afc7fc8cb8a78583
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiOptions:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
